/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import cz.zcu.kiv.ds.HelloWorldRestAPI;
import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void testAppHasAMessage() {
        assertNotNull("app should have a greeting", HelloWorldRestAPI.getMessage());
    }
}
