---
# Install PostgreSQL 10 Database Server
  
  - name: Install PostgreSQL 10
    yum: 
      name: "{{ item }}"
      state: present
    with_items:
      - postgresql10-server
      - postgresql10
