#
# ZooKeeper installation and setup
#
# See: https://www.digitalocean.com/community/tutorials/how-to-install-and-configure-an-apache-zookeeper-cluster-on-ubuntu-18-04

# - name: ZooKeeper ensemble configuration dump
#   debug:
#     msg: "{{ ensemble }}"

- name: Create Zookeeper group
  group:
    name: "{{ zookeeper_group }}"

- name: Create Zookeeper user
  user:
    name: "{{ zookeeper_user }}"
    home: "{{ zookeeper_home }}"
    groups: [ "{{ zookeeper_group }}" ]
    state: present

- name: Set Zookeeper home access rights
  file:
    path: "{{ zookeeper_home }}"
    mode: 0755

- name: Download and unpack ZooKeeper
  unarchive:
    src: "{{ zookeeper_download_url }}"
    dest: "{{ zookeeper_home }}"
    remote_src: yes
    extra_opts: [--strip-components=1]

- name: initialize ZooKeeper home
  file:
    path:  "{{ zookeeper_home }}/{{ item }}"
    state: directory
    mode: '0755'
  loop:
    - 'data'
    - 'logs'

- name: create ZooKeeper configuration file
  template:
    src: zoo.cfg.j2
    dest: "{{ zookeeper_home }}/conf/zoo.cfg"

- name: set owner
  file:
    path: "{{ zookeeper_home }}"
    owner: "{{ zookeeper_user }}"
    group: "{{ zookeeper_group }}"
    recurse: yes

- name: create ZooKeeper systemd unit file
  template:
    src: zookeeper.service.j2
    dest: /etc/systemd/system/zookeeper.service
  