Vagrant.configure("2") do |config|

    config.vm.synced_folder ".", "/vagrant"
    config.vm.box = "geerlingguy/centos7"
    config.ssh.insert_key = false
    
    config.vm.define "webserver" do |cfg|
        cfg.vm.network "private_network", ip: "10.0.1.10"
        cfg.vm.hostname = "webserver"
        config.vm.provision "shell", inline: <<-SHELL
            yum -q -y install epel-release
            yum -q -y install mc
            yum -q -y install nginx
            yum -q -y install postgresql
            systemctl start nginx
        SHELL
    end
  
    config.vm.define "dbserver" do |cfg|
        cfg.vm.network "private_network", ip: "10.0.1.11"
        cfg.vm.hostname = "dbserver"
        cfg.vm.provision "shell", #TODO: postgresql-setup initdb
            inline: <<-SHELL
                yum -q -y install epel-release
                yum -q -y install mc
                yum -q -y install postgresql-server
            SHELL
    end

end

#                 systemctl start postgresql
