#
# *** Demo 3
# Node provisioning example. Shell scripts are used for provisioning
#

Vagrant.configure("2") do |config|
    config.vm.synced_folder ".", "/vagrant"
    # common provisioning script for all nodes:
    config.vm.provision "shell", inline: <<-SHELL
        echo "Running initial common provisioning script..."
        yum update
        yum -q -y install epel-release
        yum -q -y install net-tools
        yum -q -y install mc
    SHELL

    config.vm.define "webserver" do |ws|
        ws.vm.box = "centos/8"
        ws.vm.network "private_network", ip: "10.0.1.10"
        ws.vm.hostname = "webserver"
        # provisioning script for the webserver node
        ws.vm.provision "shell", inline: <<-SHELL
            echo "Running web server provisioning script..."
            yum -q -y install nginx
            yum -q -y install postgresql
            systemctl enable nginx
            systemctl start nginx
        SHELL
    end
  
    config.vm.define "dbserver" do |db|
        db.vm.box = "centos/8"
        db.vm.network "private_network", ip: "10.0.1.11"
        db.vm.hostname = "dbserver"
        # provisioning script for the DB server node
        db.vm.provision "shell", inline: <<-SHELL
            echo "Running DB server provisioning script..."
            yum -q -y install postgresql-server
            postgresql-setup initdb
            systemctl enable postgresql
            systemctl start postgresql
        SHELL
    end

end
