require 'json'

VAGRANTFILE_API_VERSION = "2"

ENV['ANSIBLE_ROLES_PATH'] = "../ansible/roles/"

ensemble = {
  "znode-1" => { :zid => 1, :ip => "10.0.1.11", :cpus => 1, :mem => 1024 },
  "znode-2" => { :zid => 2, :ip => "10.0.1.12", :cpus => 1, :mem => 1024 },
  "znode-3" => { :zid => 3, :ip => "10.0.1.13", :cpus => 1, :mem => 1024 }
}
 
Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

    config.vm.synced_folder ".", "/vagrant"
    config.vm.box = "geerlingguy/centos7"
    config.ssh.insert_key = false

    ensemble.each_with_index do |(hostname, info), index|

        config.vm.define hostname do |cfg|
            cfg.vm.provider :virtualbox do |vb, override|
                override.vm.network :private_network, ip: "#{info[:ip]}"
                override.vm.network "forwarded_port", guest: 2181, host: (8080 + info[:zid])
                override.vm.hostname = hostname
                vb.name = hostname
                vb.customize ["modifyvm", :id, "--memory", info[:mem], "--cpus", info[:cpus], "--hwvirtex", "on"]
            end # end provider
        end # end config

    end # end ensemble

    # Ansible provisioning, see:
    # * https://www.vagrantup.com/docs/provisioning/ansible_common
    # * https://docs.ansible.com/ansible/latest/index.html
    #
    config.vm.provision :ansible do |ansible|
        ansible.compatibility_mode = "2.0"
        ansible.playbook = "zookeeper-playbook.yml"
        ansible.groups = {
            "zookeeper_ensemble" => [
                "znode-1",
                "znode-2",
                "znode-3"
            ],
            "all:vars" => {
                "mdns_subnet" => "10.0.1.0"
            },
            "zookeeper_ensemble:vars" => {
                "ensemble" => ensemble.to_json
            }
        }
    end

end
#
# EOF
#
