---
- name: Basic setup of all nodes
  hosts: all
  become: true
  roles:
    - common
    - multicast-dns

- name: Setup of the ZooKeeper ensemble
  hosts: zookeeper_ensemble
  become: true
  roles:
    - zookeeper
