#
# *** Demo 1
# Create one simple node
#

# vagrant centos config.vm.provider "docker" sshd
VAGRANTFILE_API_VERSION = "2"

# set docker as the default provider
ENV['VAGRANT_DEFAULT_PROVIDER'] = 'docker'

# disable parallellism so that the containers come up in order
ENV['VAGRANT_NO_PARALLEL'] = "1"
ENV['FORWARD_DOCKER_PORTS'] = "1"

unless Vagrant.has_plugin?("vagrant-docker-compose")
  system("vagrant plugin install vagrant-docker-compose")
  puts "Dependencies installed, please try the command again."
  exit
end

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.synced_folder ".", "/vagrant", docker_consistency: "cached"
  config.ssh.insert_key = false
  
  config.vm.define "testserver1" do |s|
    s.vm.network "private_network", ip: "10.0.1.11"
    s.vm.hostname = "testserver1"
    s.vm.provider "docker" do |d|
      d.image = "ghcr.io/maxotta/kiv-ds-docker:master"
      d.name = "testserver1"
      d.has_ssh = true
    end
  end

  config.vm.define "testserver2" do |s|
    s.vm.network "private_network", ip: "10.0.1.12"
    s.vm.hostname = "testserver2"
    s.vm.provider "docker" do |d|
      d.image = "ghcr.io/maxotta/kiv-ds-docker:master"
      d.name = "testserver2"
      d.has_ssh = true
    end
  end

end

# EOF
