#
# *** Demo 1
# Create two identical simple nodes
#

# vagrant centos config.vm.provider "docker" sshd
VAGRANTFILE_API_VERSION = "2"
# set docker as the default provider
ENV['VAGRANT_DEFAULT_PROVIDER'] = 'docker'
# disable parallellism so that the containers come up in order
ENV['VAGRANT_NO_PARALLEL'] = "1"
ENV['FORWARD_DOCKER_PORTS'] = "1"

unless Vagrant.has_plugin?("vagrant-docker-compose")
  system("vagrant plugin install vagrant-docker-compose")
  puts "Dependencies installed, please try the command again."
  exit
end

# Vagrant common configuration
Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.synced_folder ".", "/vagrant", type: "rsync", rsync__exclude: ".*/"
  config.ssh.insert_key = false
  
# Definition of node1
  config.vm.define "node1" do |s|
    s.vm.network "private_network", ip: "10.0.1.11"
    s.vm.hostname = "node1"
    s.vm.provider "docker" do |d|
      d.image = "ghcr.io/maxotta/kiv-ds-docker:v0.9.0"
      d.name = "node1"
      d.has_ssh = true
    end
    s.vm.post_up_message = "The node up and running. You can access the node with 'vagrant ssh node1'}"
  end

end

# EOF
