#
# Install hello-world-rest-api service
#

- name: create user group
  group:
    name: "{{ hello_service_group }}"

- name: create user
  user:
    name: "{{ hello_service_user }}"
    group: "{{ hello_service_group }}"
    home: "{{ hello_service_home }}" 

- name: install hello service
  unarchive:
    src: "{{ hello_service_archive }}"
    dest: "/opt"
- name: set ownership
  file:
    path: "{{ hello_service_home }}"
    owner: "{{ hello_service_user }}"
    group: "{{ hello_service_group }}"
    recurse: yes

# - name: enable search service access on the firewall
#   firewalld:
#     port: "{{ hello_service_port }}/tcp"
#     permanent: true
#     state: enabled

# - name: reload firewall configuration
#   shell: firewall-cmd --reload

- name: create hello-rest-api.service
  template:
    src: hello-rest-api.service.j2
    dest: /etc/systemd/system/hello-rest-api.service

- name: activate hello-rest-api service
  systemd:
    name: hello-rest-api
    enabled: yes
    state: started
    daemon_reload: yes

#
# EOF
# 
