#
  - name: Install software
    yum:
      name: "{{ item }}"
      state: latest
    with_items:
      - postgresql10
      - postgresql10-server

  # run checking script and echo its return value
  - name: "check if init is needed"
    shell: "{{ pg_bin_dir }}/postgresql-10-check-db-dir {{ pg_data_dir }}"
    register: dbinit
    check_mode: false
    changed_when: false
    ignore_errors: true

  # run the init only if the return value was not equal 0
  - name: "init PostgreSQL"
    shell: "{{ pg_bin_dir }}/postgresql-10-setup initdb"
    when: dbinit.rc != 0

  - name: Test successfull DB initialization
    stat:
      path: "{{ pg_data_dir }}/postgresql.conf"
    register: stat_result

  - name: Fail on DB init failure
    fail:
      msg: "DB initialization failed"
    when: stat_result.stat.exists == False 
