# https://github.com/geerlingguy/ansible-vagrant-examples
# https://www.simonholywell.com/post/2016/02/intelligent-vagrant-and-ansible-files/

Vagrant.configure("2") do |config|

    config.vm.synced_folder ".", "/vagrant"
    config.vm.box = "geerlingguy/centos7"
    config.ssh.insert_key = false

    config.vm.define "webserver-1" do |cfg|
        cfg.vm.network "private_network", ip: "10.0.1.10"
        cfg.vm.hostname = "webserver-1"
    end
  
    config.vm.define "dbserver-1" do |cfg|
        cfg.vm.network "private_network", ip: "10.0.1.11"
        cfg.vm.hostname = "dbserver-1"
    end

    config.vm.provision "ansible" do |ansible|
        ansible.compatibility_mode = "2.0"
        ansible.playbook = "provisioning/infrastructure.yml"
        ansible.groups = {
          "webservers" => ["webserver-1"],
          "dbservers" => ["dbserver-1"],
          "servers:children" => ["webservers", "dbservers"],
          "servers:vars" => {
            "mdns_subnet" => "10.0.1.0"
          },
          "dbservers:vars" => {
            "db_access_subnet" => "10.0.1.0/8"
          }
        }
      end

end
