#
# Example cluster of nodes runing an example REST API service
#

VAGRANTFILE_API_VERSION = "2"

cluster_name = "ZeroMQ"
cluster_nodes = 3
cluster_subnet = "10.0.1."

node_name = "node"
node_cpus = 1
node_mem = 512

ENV['ANSIBLE_ROLES_PATH'] = "../ansible/roles/"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

    config.vm.synced_folder ".", "/vagrant"
    config.vm.box = "geerlingguy/centos7"
    config.ssh.insert_key = false

    config.vm.provision "ansible" do |ansible|
        ansible.compatibility_mode = "2.0"
        ansible.playbook = "ansible-provision.yml"
    end

    (1..cluster_nodes).each do |i|
        ip_addr = "#{cluster_subnet}#{100 + i}"
        hostname = "#{node_name}-#{i}"
        vmname = "#{cluster_name}_#{hostname}"
        config.vm.define "#{hostname}" do |cfg|
            cfg.vm.post_up_message = "REST API Call: curl -H 'Accept: application/json' http://#{ip_addr}:8080/hello"
            cfg.vm.network "private_network", ip: "#{ip_addr}"
            cfg.vm.hostname = "#{hostname}"
            cfg.vm.provider :virtualbox do |vb|
                vb.name = "#{vmname}"
                vb.customize ["modifyvm", :id, "--memory", node_mem, "--cpus", node_cpus, "--hwvirtex", "on"]
            end # end provider
        end # end config
    end # end cluster
end

#
# EOF
#

