VAGRANTFILE_API_VERSION = "2"

cluster_id = "0mq"
cluster = {
  "node-1" => { :ip => "10.0.1.11", :cpus => 1, :mem => 512 },
  "node-2" => { :ip => "10.0.1.12", :cpus => 1, :mem => 512 },
  "node-3" => { :ip => "10.0.1.13", :cpus => 1, :mem => 512 }
}

ENV['ANSIBLE_ROLES_PATH'] = "../ansible/roles/"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

    config.vm.synced_folder ".", "/vagrant"
    config.vm.box = "geerlingguy/centos7"
    config.ssh.insert_key = false

    cluster.each_with_index do |(hostname, info), index|

        config.vm.define hostname do |cfg|
            cfg.vm.provider :virtualbox do |vb, override|
                override.vm.network :private_network, ip: "#{info[:ip]}"
                override.vm.hostname = hostname
                vb.name = cluster_id + "_" + hostname
                vb.customize ["modifyvm", :id, "--memory", info[:mem], "--cpus", info[:cpus], "--hwvirtex", "on"]
                config.vm.provision "ansible" do |ansible|
                    ansible.compatibility_mode = "2.0"
                    ansible.playbook = "ansible-provision.yml"
                    # ansible.groups = {}
                  end
                        end # end provider
        end # end config
    end # end cluster
end
#
# EOF
#

