#
# *** Demo 2
# Create two nodes with gived IP addresses and names
#

Vagrant.configure("2") do |config|
    # shared folder - the current project directory is mounted at /vagrant on both nodes
    config.vm.synced_folder ".", "/vagrant"

    config.vm.define "webserver" do |ws|
        ws.vm.box = "centos/8"
        ws.vm.network "private_network", ip: "10.0.1.10"
        ws.vm.hostname = "webserver"
    end
  
    config.vm.define "dbserver" do |db|
        db.vm.box = "centos/8"
        db.vm.network "private_network", ip: "10.0.1.11"
        db.vm.hostname = "dbserver"
    end
end

# EOF
